# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Is_staff',
            new_name='is_staff',
        ),
    ]
